### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by Git-Ross** [MrTronMan/Amend#12]
Hi,

When shutting down or restarting my server, Amend downloads the latest purpur.jar but is unable to replace the existing jar due to it being used by another service (control panel?). I am using the Crafty Controller control panel.

```
[13:22:04 WARN]: [Amend] -------------------------------
[13:22:04 INFO]: [Amend] Amend
[13:22:04 INFO]: [Amend] Server-Type Selected: PURPUR
[13:22:04 INFO]: [Amend] Current Version: 2250 (MC: 1.21)
[13:22:04 WARN]: [Amend] Version is NOT up to date! Newest PURPUR version is 2251
[13:22:04 INFO]: [Amend] Downloading update and applying to purpur.jar...
[13:22:04 WARN]: java.nio.file.FileSystemException: purpur.jar: The process cannot access the file because it is being used by another process
[13:22:04 WARN]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[13:22:04 WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[13:22:04 WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[13:22:04 WARN]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:273)
[13:22:04 WARN]: 	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:109)
[13:22:04 WARN]: 	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
[13:22:04 WARN]: 	at java.base/java.nio.file.Files.copy(Files.java:3133)
[13:22:04 WARN]: 	at Amend-1.7.6--V.1.21.jar//com.tronmc.beta.amend.Amend.onDisable(Amend.java:199)
[13:22:04 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[13:22:04 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237)
[13:22:04 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161)
[13:22:04 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97)
[13:22:04 WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541)
[13:22:04 WARN]: 	at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:612)
[13:22:04 WARN]: 	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:999)
[13:22:04 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:881)
[13:22:04 WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1330)
[13:22:04 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332)
[13:22:04 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by MrTronMan** [comment]
Hi! I apologize for the late reply, are you by chance using Windows?

**Comment by Git-Ross** [comment]
Yes, Windows 10

**Comment by MrTronMan** [comment]
Ah, okay that makes more sense.  In reference to #7, Windows tends to the following.

> Hi. Yes, I did some tests myself and such; since MCSS is its own application and not straight up started from the jar, Windows (more specifically Java honestly) will not let Amend access purpur.jar (since MCSS is reading and launching purpur.jar from its program and not just running the jar itself). Amend updates by saving all your worlds (to avoid any corruption) and while the server is running (technically), it will replace the jar upon shutdown and since the jar itself is what's running it will replace the file with no problem. However, with MCSS, Amend can't do anything with the jar or replace it since MCSS is the one opening it and accessing it 24/7. Unfortunately, I don't think there is a way around this. Unless Amend were to create a separate .jar and you would have to delete the old one every time it updated. I can do some more digging if you'd like?

To sum it up, Windows filesystems are different than Linux ones and Windows doesn't allow access to the jar as it's directly being used. I also have Crafty Controller (a fantastic piece of software) but I run it on Linux. I have tried to see if there was a way to make this work, but I am 95% sure I would have to create a separate exe. I will see what I can do though!

**Comment by Git-Ross** [comment]
Hi,

Thanks for the information, its pretty much what I thought was happening!

I have managed to create a solution for my use case in the form of a Powershell script that grabs the latest release, downloads it and then stores it until my daily backup occurs (3am, server is offline for 15 minutes anyway) at which point the purpur.jar is replaced. With this in mind, please don't feel the need to investigate further for me but if you do find a solution and would like me to test it, feel free to let me know!

Thanks.

**Comment by MrTronMan** [comment]
Hi! I would love it if you could email me the Powershell Script (without any of your information of course) and I might go off of that to create a solution because, the only real way I could find a solution was to physically have the Amend.jar run and then execute the purpur/paper.jar separately.

You can drop the email by @ will@mrtron.dev, if you wish.

Thank you!

**Comment by Git-Ross** [comment]
Hi,

Feel free to have a look at my repository (https://github.com/Git-Ross/PurpurMC-Auto-Updater-for-Windows). It should give you a insight off how I went about it.

I would love to have a look through your plugin (as a learning tool more then anything) when I get a chance and see if I can come up with a solution! 

Let me know if your able to figure anything out.

**Comment by MrTronMan** [comment]
Hello! As you can see I have added updates referencing this issue. I noticed Crafty had an Executable URL (being a Crafty user myself) hoping to allow more Windows users, I created in my API a way to get this.
I know you have your PowerShell script but this is my temporary fix for others with Crafty.

If you do want to test it there is the README or you are welcome to look through my quickly written-up docs @ [api.tronmc.com](https://api.tronmc.com)

Let me know! 😄
