### ISSUE TITLE
Not working on Windows based server

### ISSUE THREAD

**Issue by sybenx** [MrTronMan/Amend#7]
**Describe the problem**
Amend fails to update Paper server

**To Reproduce**
1. Run server with Amend
2. Shutdown server with "stop" command
3. See Amend error

**Info:**
 Please add the following info below so I can have an understanding.

*Version of MC:* `1.19.4`
*Version of Amend:* `1.6 v1.19.4`
*Server-Type:* `paper`
*Host (if there is any):* `n/a`

**Additional content**

```
[08:08:51 INFO]: Timings Reset
[08:08:56 INFO]: Stopping the server
[08:08:56 INFO]: Stopping server
[08:08:56 INFO]: [Amend] Disabling Amend v1.6--V.1.19.4
[08:08:56 INFO]: [Amend] Started Update Check...
[08:09:03 WARN]: [Amend] -------------------------------
[08:09:03 INFO]: [Amend] Amend
[08:09:03 INFO]: [Amend] Server-Type Selected: PAPER
[08:09:03 INFO]: [Amend] Current Version: 67 (MC: 1.19.4)
[08:09:03 WARN]: [Amend] Version is NOT up to date! Newest PAPER version is 484
[08:09:03 INFO]: [Amend] Downloading update and applying to paper.jar...
[08:09:03 WARN]: [Amend] Plugin Amend v1.6--V.1.19.4 generated an exception while executing task 2
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[paper-1.19.4.jar:git-Paper-467]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[paper-1.19.4.jar:git-Paper-467]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[paper-1.19.4.jar:git-Paper-467]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:176) ~[paper-1.19.4.jar:git-Paper-467]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:145) ~[paper-1.19.4.jar:git-Paper-467]
	at com.tronmc.beta.amend.UpdateChecker.G(Unknown Source) ~[Amend-1.6--V.1.19.4.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-467]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-467]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:09:15 WARN]: java.nio.file.FileSystemException: paper.jar: The process cannot access the file because it is being used by another process
[08:09:15 WARN]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[08:09:15 WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[08:09:15 WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[08:09:15 WARN]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[08:09:15 WARN]: 	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
[08:09:15 WARN]: 	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
[08:09:15 WARN]: 	at java.base/java.nio.file.Files.copy(Files.java:3148)
[08:09:15 WARN]: 	at Amend-1.6--V.1.19.4.jar//com.tronmc.beta.amend.Amend.onDisable(Amend.java:138)
[08:09:15 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[08:09:15 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227)
[08:09:15 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:151)
[08:09:15 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92)
[08:09:15 WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528)
[08:09:15 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.disablePlugins(CraftServer.java:486)
[08:09:15 WARN]: 	at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:946)
[08:09:15 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:804)
[08:09:15 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1212)
[08:09:15 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[08:09:15 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by MrTronMan** [comment]
Thank you, I will do a little testing for myself to see. Please give me an hour or two (most likely less) to look through it. Thank you for using Amend! 😁
@sybenx

**Comment by MrTronMan** [comment]
Hi, @sybenx could you please try redownloading from the Amend website and try downloading 1.6.1 (the version that just released) and try again and then see if the same bug happens? It could be a corruption or a one-time thing.

**Comment by MrTronMan** [comment]
Just following up if everything is working and if there are any issues?

**Comment by sybenx** [comment]
I'm still having this issue

```
[15:18:37] [MCSS][Info] Your server will restart any moment now.
[15:18:37 INFO]: Stopping the server
[15:18:37 INFO]: Stopping server
[15:18:37 INFO]: [Amend] Disabling Amend v1.6.1--V.1.19.4
[15:18:37 INFO]: [Amend] Started Update Check...
[15:18:38 WARN]: [Amend] -------------------------------
[15:18:38 INFO]: [Amend] Amend
[15:18:38 INFO]: [Amend] Server-Type Selected: PAPER
[15:18:38 INFO]: [Amend] Current Version: 484 (MC: 1.19.4)
[15:18:38 WARN]: [Amend] Version is NOT up to date! Newest PAPER version is 491
[15:18:38 INFO]: [Amend] Downloading update and applying to paper.jar...
[15:18:50 WARN]: java.nio.file.FileSystemException: paper.jar: The process cannot access the file because it is being used by another process
[15:18:50 WARN]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[15:18:50 WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[15:18:50 WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[15:18:50 WARN]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[15:18:50 WARN]: 	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
[15:18:50 WARN]: 	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
[15:18:50 WARN]: 	at java.base/java.nio.file.Files.copy(Files.java:3148)
[15:18:50 WARN]: 	at Amend-1.6.1--V.1.19.4.jar//com.tronmc.beta.amend.Amend.onDisable(Amend.java:138)
[15:18:50 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[15:18:50 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227)
[15:18:50 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:151)
[15:18:50 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92)
[15:18:50 WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528)
[15:18:50 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.disablePlugins(CraftServer.java:486)
[15:18:50 WARN]: 	at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:947)
[15:18:50 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:804)
[15:18:50 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1213)
[15:18:50 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[15:18:50 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by sybenx** [comment]
i tried a different server, different network, and i got the same error. The common factor was that I set up the server using MC Server Soft. But whether I run the server through that wrapper or by directly clicking the paper.jar, I get the same amend error.

**Comment by MrTronMan** [comment]
Hi. Yes, I did some tests myself and such; since MCSS is its own application and not straight up started from the jar, Windows (more specifically Java honestly) will not let Amend access `purpur.jar` (since MCSS is reading and launching `purpur.jar` from its program and not just running the jar itself). Amend updates by saving all your worlds (to avoid any corruption) and while the server is running (technically), it will replace the jar upon shutdown and since the jar itself is what's running it will replace the file with no problem. However, with MCSS, Amend can't do anything with the jar or replace it since MCSS is the one opening it and accessing it 24/7. Unfortunately, I don't think there is a way around this. Unless Amend were to create a separate `.jar` and you would have to delete the old one every time it updated. I can do some more digging if you'd like?

@sybenx

**Comment by MrTronMan** [comment]
Closed due to inactivity.
If you wish to, you may reopen the issue.

**Comment by sybenx** [comment]
How are you launching the server when amend works? When I double click paper.jar to launch it, it does the same thing

**Comment by MrTronMan** [comment]
I run mine on Linux Servers, you have Windows 10 (or 11). Windows file systems force the jar locked and Amend is not able to bypass it because Windows locks it, unlike Linux where you're able to swap it out. Amend changes the file right before shutdown which means the jar is still technically running. If the jar was accessible that means that the jar isn't running but then that means Amend doesn't run. I can try to see if I can find a workaround but there really isn't a way since it is OS locked. To check, you are using Windows, right?

**Comment by sybenx** [comment]
You are correct, that server is on windows. That explains it, thanks!

**Comment by MrTronMan** [comment]
Yeah, I'm sorry it's just a Windows thing, I appreciate you attempting to use it...I might end up trying to find a way for this to work on Windows so this gives me an idea. Thank you!
